In [2]:
import cv2

In [3]:
img = cv2.imread("images/galaxy.jpg", 0)

In [4]:
print(type(img))
print(img)
print(img.shape)

<class 'numpy.ndarray'>
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
(1485, 990)


In [5]:
resized_image = cv2.resize(img, (img.shape[1]/2,img.shape[0]/2))

In [7]:
cv2.imshow("Galaxy", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
